GET http://127.0.0.1:8090/api/crud/users
Accept: application/json

###
POST http://127.0.0.1:8090/api/crud/users
Accept: application/json
Content-Type: application/json

{
  "email": "user@example.tld",
  "password": "admin"
}

###
POST http://127.0.0.1:8000/api/public/test